### ISSUE TITLE
Constant errors from KeyError: 'icon' in forecast update

### ISSUE THREAD

**Issue by mjmeli** [briis/hass-weatherflow2mqtt#142]
### Home Assistant Version?

2021.12.8

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

3.0.6

### What happened?

I'm seeing these KeyError errors in the logs constantly. Sometimes every minute or so, sometimes more spaced out. It seems like they are causing the container to crash and restart. In the past 3 errors, I've seen this error nearly 50 times.

### Relevant log output

```
2022-01-11T18:11:03.882738552Z Traceback (most recent call last):
2022-01-11T18:11:03.883204217Z   File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>
2022-01-11T18:11:03.939501607Z     sys.exit(load_entry_point('weatherflow2mqtt==3.0.6', 'console_scripts', 'weatherflow2mqtt')())
2022-01-11T18:11:03.939670628Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/__main__.py", line 10, in main
2022-01-11T18:11:03.939781507Z   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2022-01-11T18:11:04.007419904Z     return loop.run_until_complete(main)
2022-01-11T18:11:04.007921460Z   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2022-01-11T18:11:04.081584981Z     return future.result()
2022-01-11T18:11:04.081732024Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 808, in main
2022-01-11T18:11:04.081845657Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 214, in run_time_based_updates
2022-01-11T18:11:04.081902245Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 721, in _update_forecast
2022-01-11T18:11:04.081942788Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/forecast.py", line 147, in update_forecast
2022-01-11T18:11:04.082036091Z KeyError: 'icon'
2022-01-11T18:11:19.028129429Z INFO:weatherflow2mqtt.weatherflow_mqtt:Timezone is America/New_York
2022-01-11T18:11:19.524789009Z INFO:weatherflow2mqtt.weatherflow_mqtt:Connected to the MQTT server at 192.168.86.28:1883
2022-01-11T18:11:19.525461377Z INFO:weatherflow2mqtt.weatherflow_mqtt:The UDP server is listening on port 50222
2022-01-11T18:11:27.930221535Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Status
2022-01-11T18:11:27.930745811Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Weather
2022-01-11T18:11:28.458225827Z ERROR:asyncio:Task exception was never retrieved
2022-01-11T18:11:28.458376442Z future: <Task finished name='Task-4' coro=<WeatherFlowMqtt._update_forecast() done, defined at /usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py:716> exception=KeyError('icon')>
2022-01-11T18:11:28.458505806Z Traceback (most recent call last):
2022-01-11T18:11:28.458542325Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 721, in _update_forecast
2022-01-11T18:11:28.458612987Z     if any(forecast := await self.forecast.update_forecast()):
2022-01-11T18:11:28.458649816Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/forecast.py", line 147, in update_forecast
2022-01-11T18:11:28.458712286Z     ATTR_FORECAST_CONDITION: self.ha_condition_value(row["icon"]),
2022-01-11T18:11:28.458746821Z KeyError: 'icon'
2022-01-11T18:11:33.324193690Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Status
2022-01-11T18:11:33.324667009Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Absolute Humidity
2022-01-11T18:11:33.326294505Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Air Density
2022-01-11T18:11:33.326519117Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Temperature
2022-01-11T18:11:33.326771015Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Voltage
[more of the above logs cut for brevity]
2022-01-11T18:11:33.340920046Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Wind Speed
2022-01-11T18:11:33.341109714Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Wind Speed Avg
2022-01-11T18:12:20.831432824Z Traceback (most recent call last):
2022-01-11T18:12:20.831902001Z   File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>
2022-01-11T18:12:20.872820402Z     sys.exit(load_entry_point('weatherflow2mqtt==3.0.6', 'console_scripts', 'weatherflow2mqtt')())
2022-01-11T18:12:21.311346450Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/__main__.py", line 10, in main
2022-01-11T18:12:21.311442989Z   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2022-01-11T18:12:21.311493278Z     return loop.run_until_complete(main)
2022-01-11T18:12:21.311527320Z   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2022-01-11T18:12:21.311564613Z     return future.result()
2022-01-11T18:12:21.311604020Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 808, in main
2022-01-11T18:12:21.311645789Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 214, in run_time_based_updates
2022-01-11T18:12:21.311685628Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 721, in _update_forecast
2022-01-11T18:12:21.311724357Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/forecast.py", line 147, in update_forecast
2022-01-11T18:12:21.311760301Z KeyError: 'icon'
2022-01-11T18:12:43.078432940Z INFO:weatherflow2mqtt.weatherflow_mqtt:Timezone is America/New_York
2022-01-11T18:12:43.643495153Z INFO:weatherflow2mqtt.weatherflow_mqtt:Connected to the MQTT server at 192.168.86.28:1883
2022-01-11T18:12:43.645317890Z INFO:weatherflow2mqtt.weatherflow_mqtt:The UDP server is listening on port 50222
2022-01-11T18:12:47.969995600Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Status
2022-01-11T18:12:47.971434287Z INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Weather
2022-01-11T18:12:48.829227737Z ERROR:asyncio:Task exception was never retrieved
2022-01-11T18:12:49.083971761Z future: <Task finished name='Task-4' coro=<WeatherFlowMqtt._update_forecast() done, defined at /usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py:716> exception=KeyError('icon')>
2022-01-11T18:12:49.084077010Z Traceback (most recent call last):
2022-01-11T18:12:49.084112394Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 721, in _update_forecast
2022-01-11T18:12:49.084152213Z     if any(forecast := await self.forecast.update_forecast()):
2022-01-11T18:12:49.084186074Z   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-3.0.6-py3.9.egg/weatherflow2mqtt/forecast.py", line 147, in update_forecast
2022-01-11T18:12:49.084222570Z     ATTR_FORECAST_CONDITION: self.ha_condition_value(row["icon"]),
2022-01-11T18:12:49.084253324Z KeyError: 'icon'
```

**Comment by briis** [comment]
It is the Weather Forecast that fails. Have you entered a valid Station ID and related API Token?

**Comment by mjmeli** [comment]
I do, and it's been working for months. I can try generating a new token.

```
  weatherflow2mqtt:
    container_name: weatherflow2mqtt
    image: briis/weatherflow2mqtt:latest
    restart: unless-stopped
    volumes:
      - /volume1/docker/weatherflow2mqtt/config:/data
    ports:
      - 0.0.0.0:50222:50222/udp
    environment:
      - TZ=America/New_York
      - UNIT_SYSTEM=imperial
      - LANGUAGE=en
      - RAPID_WIND_INTERVAL=60
      - DEBUG=False
      - ELEVATION=114 #in meters
      - WF_HOST=0.0.0.0
      - WF_PORT=50222
      - MQTT_HOST=192.168.86.28
      - MQTT_PORT=1883
      - MQTT_USERNAME=xxx
      - MQTT_PASSWORD=xxx
      - MQTT_DEBUG=False
      - ADD_FORECAST=True #goes to REST API
      - STATION_ID=xxxx
      - STATION_TOKEN=xxxx
      - FORECAST_INTERVAL=30 #minute between forecast updates
      ```

**Comment by briis** [comment]
Would you mind sharing the Station ID. Then I can check the raw data from WeatherFlow, to see if there is something wrong.

Btw: You can remove `ADD_FORECAST` as this is no longer used. If `STATION_ID` and `STATION_TOKEN` are filled out, the forecast will be loaded.

**Comment by mjmeli** [comment]
A new token did not work. The station ID is 54213

**Comment by briis** [comment]
For some reason WeatherFlow returns bad data for Day 8 in the Daily forecast. Below You can see the difference between Day 7 and Day 8 and the Icon is missing for Day 8. I will make some changes to avoid crashing on the error.

```json
      {
        "day_start_local": 1642482000,
        "day_num": 18,
        "month_num": 1,
        "conditions": "Snow Possible",
        "icon": "possibly-snow-day",
        "sunrise": 1642508631,
        "sunset": 1642544867,
        "air_temp_high": 7,
        "air_temp_low": -2,
        "precip_probability": 20,
        "precip_icon": "chance-snow",
        "precip_type": "snow"
      },
      {
        "day_start_local": 1642568400,
        "day_num": 19,
        "month_num": 1,
        "conditions": "",
        "sunrise": 1642595008,
        "sunset": 1642631328,
        "air_temp_high": 8,
        "air_temp_low": -4,
        "precip_probability": 20
      },
````

**Comment by briis** [comment]
I have just published a new build with the `dev` tag which contains the fix. Could you change `latest` to `dev` in your composer file and try again. Please post here if successful.

**Comment by mjmeli** [comment]
Yep, the `dev` image is working for me. Thanks

**Comment by mjmeli** [comment]
The new `latest` is now also working. Thanks again - I'll close this now
