### ISSUE TITLE
 reported a sensor fault. Reason: ['lightning disturber'] system fault 

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#34]
With:

ENV ADD_FORECAST=True

INFO:__main__:SETTING UP Battery TEMPEST SENSOR,
INFO:__main__:SETTING UP Solar Radiation SENSOR,
INFO:__main__:SETTING UP Precipitation Type SENSOR,
INFO:__main__:SETTING UP Last Rain start SENSOR,
INFO:__main__:SETTING UP Air Density SENSOR,
INFO:__main__:SETTING UP Dew Point SENSOR,
INFO:__main__:SETTING UP Rain Rate SENSOR,
INFO:__main__:SETTING UP Uptime SENSOR,
INFO:__main__:SETTING UP Feels Like Temperature SENSOR,
INFO:__main__:SETTING UP Visibility SENSOR,
INFO:__main__:SETTING UP Wet Bulb Temperature SENSOR,
INFO:__main__:SETTING UP Delta T SENSOR,
INFO:__main__:SETTING UP Dewpoint Comfort Level SENSOR,
INFO:__main__:SETTING UP Temperature Level SENSOR,
INFO:__main__:SETTING UP UV Level SENSOR,
INFO:__main__:SETTING UP Beaufort Scale SENSOR,
INFO:__main__:SETTING UP Weather SENSOR,
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber'],
Traceback (most recent call last):,
  File "/app/weatherflow_mqtt.py", line 499, in <module>,
    asyncio.run(main()),
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run,
    return loop.run_until_complete(main),
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete,
    return future.result(),
  File "/app/weatherflow_mqtt.py", line 180, in main,
    condition_data, fcst_data  = await forecast.update_forecast(),
  File "/app/forecast.py", line 99, in update_forecast,
    ATTR_FORECAST_CONDITION: await self.ha_condition_value(row["icon"]),,
KeyError: 'icon',
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
INFO:__main__:Connected to the MQTT server on address 127.0.0.1 and port 1883...,
INFO:__main__:The UDP server is running on port 50222...,
INFO:__main__:Defining Sensors for Home Assistant,
INFO:__main__:SETTING UP Wind Speed SENSOR,
INFO:__main__:SETTING UP Wind Bearing SENSOR,
INFO:__main__:SETTING UP Wind Direction SENSOR,
INFO:__main__:SETTING UP Station Pressure SENSOR,
INFO:__main__:SETTING UP Sea Level Pressure SENSOR,
INFO:__main__:SETTING UP Pressure Trend SENSOR,
INFO:__main__:SETTING UP Temperature SENSOR,
INFO:__main__:SETTING UP Humidity SENSOR,
INFO:__main__:SETTING UP Lightning Count (3 hours) SENSOR,
INFO:__main__:SETTING UP Lightning Count (Today) SENSOR,
INFO:__main__:SETTING UP Lightning Distance SENSOR,
INFO:__main__:SETTING UP Lightning Energy SENSOR,
INFO:__main__:SETTING UP Last Lightning Strike SENSOR,
INFO:__main__:SETTING UP Illuminance SENSOR,
INFO:__main__:SETTING UP UV Index SENSOR,
INFO:__main__:SETTING UP Rain Today SENSOR,
INFO:__main__:SETTING UP Rain Yesterday SENSOR,
INFO:__main__:SETTING UP Rain Duration (Today) SENSOR,
INFO:__main__:SETTING UP Rain Duration (Yesterday) SENSOR,
INFO:__main__:SETTING UP Wind Lull SENSOR,
INFO:__main__:SETTING UP Wind Speed Avg SENSOR,
INFO:__main__:SETTING UP Wind Gust SENSOR,
INFO:__main__:SETTING UP Wind Bearing Avg SENSOR,
INFO:__main__:SETTING UP Wind Direction Avg SENSOR,
INFO:__main__:SETTING UP Battery TEMPEST SENSOR,
INFO:__main__:SETTING UP Solar Radiation SENSOR,
INFO:__main__:SETTING UP Precipitation Type SENSOR,
INFO:__main__:SETTING UP Last Rain start SENSOR,
INFO:__main__:SETTING UP Air Density SENSOR,
INFO:__main__:SETTING UP Dew Point SENSOR,
INFO:__main__:SETTING UP Rain Rate SENSOR,
INFO:__main__:SETTING UP Uptime SENSOR,
INFO:__main__:SETTING UP Feels Like Temperature SENSOR,
INFO:__main__:SETTING UP Visibility SENSOR,
INFO:__main__:SETTING UP Wet Bulb Temperature SENSOR,
INFO:__main__:SETTING UP Delta T SENSOR,
INFO:__main__:SETTING UP Dewpoint Comfort Level SENSOR,
INFO:__main__:SETTING UP Temperature Level SENSOR,
INFO:__main__:SETTING UP UV Level SENSOR,
INFO:__main__:SETTING UP Beaufort Scale SENSOR,
INFO:__main__:SETTING UP Weather SENSOR,
Traceback (most recent call last):,
  File "/app/weatherflow_mqtt.py", line 499, in <module>,
    asyncio.run(main()),
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run,
    return loop.run_until_complete(main),
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete,
    return future.result(),
  File "/app/weatherflow_mqtt.py", line 180, in main,
    condition_data, fcst_data  = await forecast.update_forecast(),
  File "/app/forecast.py", line 99, in update_forecast,
    ATTR_FORECAST_CONDITION: await self.ha_condition_value(row["icon"]),,
KeyError: 'icon',

**Comment by briis** [comment]
Did you retrieve your personal token, and add this to STATION_TOKEN in the docker run command?

**Comment by robertw** [comment]
yes it is my info

**Comment by briis** [comment]
I was actually looking for the actual docker run command, like this:

````
docker run -d \
--name=weatherflow2mqtt --restart=unless-stopped \
-v $(pwd):/usr/local/config \
-p 0.0.0.0:50222:50222/udp \
-e TZ=Europe/Copenhagen \
-e TEMPEST_DEVICE=True \
-e UNIT_SYSTEM=metric \
-e LANGUAGE=en \
-e RAPID_WIND_INTERVAL=0 \
-e DEBUG=False \
-e ELEVATION=53 \
-e WF_HOST=0.0.0.0 \
-e WF_PORT=50222 \
-e MQTT_HOST=192.168.3.10 \
-e MQTT_PORT=1883 \
-e MQTT_USERNAME= xxxxxxxx\
-e MQTT_PASSWORD= xxxxxxxx\
-e MQTT_DEBUG=False \
-e ADD_FORECAST=True \
-e STATION_ID= 2777\
-e STATION_TOKEN= xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
-e FORECAST_INTERVAL=30 \
ghcr.io/briis/hass-weatherflow2mqtt:latest
````
> DEBUG:main:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber']

This is a Fault that your station reports. I am not doing anything about it, just reporting it, and it might affect the Lightning counts you are getting. You could try and report this to WeatherFlow, to see if they can update your FW on the device or Hub.

**Comment by robertw** [comment]
Sorry I didn't get back to you earlier I had gallbladder surgery so I'm
going to be out of commission for a few days in the meantime I've made a
request for firmware update and if you could possibly let me know what
version of firmware that you're running that would be a great help....
Regards Robert

**Comment by briis** [comment]
Ohh, I hope you are well now?

My HUB FW is 169, and Tempest FW is 156

**Comment by robertw** [comment]
First off still in the recovery mode but should be back on my feet within
the week here is the response from weather flow I checked your version to
my version My hub version is behind you my station version is in front of
you

My station version is 170 and my hub version is 153 I've asked them to push
the most current versions to my device but for the sounds of things maybe
what you're picking up should be ignored you know better than I do hope
this is of some assistance and thank you once again for your amazing work


*Alex S.* (WeatherFlow Support)

Jul 2, 2021, 11:29 EDT
Hi Robert,

You are on the current firmware for the Tempest. The lightning disturber
message means that the lightning sensor is working correctly. It is seeing
other electrical signals and filtering them out so that they don't get
reported as false lightning. You can look in the status portion of the app
to see your firmware version. (Settings>Stations>Select your
station>Status>Scrolls down to the Tempest portion and view the firmware
version) Please feel free to reach back out with any other questions or
concerns.

Kind Regards,
Alex Smith
WeatherFlow Support

**Comment by briis** [comment]
Good to hear, and hope your recovery will go fine.

Yes, what he is writing is correct. You should look for something close to your station that can create these electrical signals and if possible remove them or move your station to another location. But as I said, I also filter them out in the program, but I do report them, so that we also locally can see, that there might be disturbance.

So, is your station working now, or are you still having issues?

**Comment by robertw** [comment]
Good day sir the problem that still is is when the error comes up where the
report comes up and it's going out to get information from the website
meaning that I put in my API key and station ID the in the forecast value
is true your program halts as the original log that I sent you and for
whatever reason I'm unable to restart the program I have to clear out the
database and then restart so the real issue is I believe the error and how
it's handled some way is causing a problem when it's trying to match it
with the forecast information I hope that helps the station is working just
fine even though it is reporting the information and the erroneous
lightning strikes but that according to weather flow is correct....

**Comment by briis** [comment]
A question: Did you edit the file `Dockerfile` ? It seems to me that you have? If you have, pull the original version back and then instead open a terminal and execute this command: (Remember to change MQTT IP, Station Token and other values specific to you.

Also, try and run this command with `sudo` in front, to see if that helps.

```bash
docker run -d \
--name=weatherflow2mqtt --restart=unless-stopped \
-v $(pwd):/usr/local/config \
-p 0.0.0.0:50222:50222/udp \
-e TZ=America/New_York \
-e TEMPEST_DEVICE=True \
-e UNIT_SYSTEM=imperial \
-e LANGUAGE=en \
-e RAPID_WIND_INTERVAL=0 \
-e DEBUG=False \
-e ELEVATION=0 \
-e WF_HOST=0.0.0.0 \
-e WF_PORT=50222 \
-e MQTT_HOST=192.168.3.10 \
-e MQTT_PORT=1883 \
-e MQTT_USERNAME= xxxxxxxx\
-e MQTT_PASSWORD= xxxxxxxx\
-e MQTT_DEBUG=False \
-e ADD_FORECAST=True \
-e STATION_ID= 52975\
-e STATION_TOKEN= xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
-e FORECAST_INTERVAL=30 \
ghcr.io/briis/hass-weatherflow2mqtt:latest
````

**Comment by robertw** [comment]
Good day : I am still learning gig time here I am running on a pi 4 so i am using Portainer to create the image and running it so I do the following even thought it maybe wrong as I am doing this for the first time I download your code to local folder edit your docker file then upload it to Portainer and then create the image and run it .....thank you for your patience  i don't see where i can run your docker command while running hassio

**Comment by robertw** [comment]
Just a fyi updated to new 209 no problems to show but no lighting today as of yet but will know tonight more storms coming
also my wife created a Spanish translation file for you .....many thanks regards

**Comment by briis** [comment]
Perfect, thanks 🙏

**Comment by robertw** [comment]
Well everything was working fine until the weather changed and we had lightning the following errors reappeared.... The version error I know why is not showing up because I'm not carrying the version forward but all the other areas I really don't understand I truly wish I could be of more help the doctor settings as per your file are exactly the same


DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
ERROR:__main__:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused,
DEBUG:asyncio:Using selector: EpollSelector,
INFO:__main__:Timezone is America/New_York,
ERROR:helpers:Could not find VERSION File.,
INFO:__main__:Connected to the MQTT server on address 127.0.0.1 and port 1883...,
INFO:__main__:The UDP server is running on port 50222...,
INFO:__main__:Defining Sensors for Home Assistant,
INFO:__main__:SETTING UP Wind Speed SENSOR,
INFO:__main__:SETTING UP Wind Bearing SENSOR,
INFO:__main__:SETTING UP Wind Direction SENSOR,
INFO:__main__:SETTING UP Station Pressure SENSOR,
INFO:__main__:SETTING UP Sea Level Pressure SENSOR,
INFO:__main__:SETTING UP Pressure Trend SENSOR,
INFO:__main__:SETTING UP Temperature SENSOR,
INFO:__main__:SETTING UP Humidity SENSOR,
INFO:__main__:SETTING UP Lightning Count (3 hours) SENSOR,
INFO:__main__:SETTING UP Lightning Count (Today) SENSOR,
INFO:__main__:SETTING UP Lightning Distance SENSOR,
INFO:__main__:SETTING UP Lightning Energy SENSOR,
INFO:__main__:SETTING UP Last Lightning Strike SENSOR,
INFO:__main__:SETTING UP Illuminance SENSOR,
INFO:__main__:SETTING UP UV Index SENSOR,
INFO:__main__:SETTING UP Rain Today SENSOR,
INFO:__main__:SETTING UP Rain Yesterday SENSOR,
INFO:__main__:SETTING UP Rain Duration (Today) SENSOR,
INFO:__main__:SETTING UP Rain Duration (Yesterday) SENSOR,
INFO:__main__:SETTING UP Wind Lull SENSOR,
INFO:__main__:SETTING UP Wind Speed Avg SENSOR,
INFO:__main__:SETTING UP Wind Gust SENSOR,
INFO:__main__:SETTING UP Wind Bearing Avg SENSOR,
INFO:__main__:SETTING UP Wind Direction Avg SENSOR,
INFO:__main__:SETTING UP Battery TEMPEST SENSOR,
INFO:__main__:SETTING UP Solar Radiation SENSOR,
INFO:__main__:SETTING UP Precipitation Type SENSOR,
INFO:__main__:SETTING UP Last Rain start SENSOR,
INFO:__main__:SETTING UP Air Density SENSOR,
INFO:__main__:SETTING UP Dew Point SENSOR,
INFO:__main__:SETTING UP Rain Rate SENSOR,
INFO:__main__:SETTING UP Uptime SENSOR,
INFO:__main__:SETTING UP Feels Like Temperature SENSOR,
INFO:__main__:SETTING UP Visibility SENSOR,
INFO:__main__:SETTING UP Wet Bulb Temperature SENSOR,
INFO:__main__:SETTING UP Delta T SENSOR,
INFO:__main__:SETTING UP Dewpoint Comfort Level SENSOR,
INFO:__main__:SETTING UP Temperature Level SENSOR,
INFO:__main__:SETTING UP UV Level SENSOR,
INFO:__main__:SETTING UP Beaufort Scale SENSOR,
INFO:__main__:SETTING UP Weather SENSOR,
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed'],
DEBUG:__main__:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed'],

**Comment by robertw** [comment]
I could not clear the fault but i deleted the data base the system returned to normal so it leads me to believe that the problem is in the data base logic even though it appears to be a system fault. cheers

**Comment by robertw** [comment]
Good day sir
just upgraded to news revised build:

moved it out to a dedicated raspberry pi clean docker setup and python 3.9.6
we are getting the same errors

looking like it has to do with the sql update

2021-07-11T16:15:06.785921872Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:DEVICE STATUS TRIGGERED AT 2021-07-11 12:15:06.783805

2021-07-11T16:15:06.786050630Z   -- Device: ST-00019259

2021-07-11T16:15:06.786131185Z  -- Firmware Revision: 156

2021-07-11T16:15:06.786190980Z  -- Voltage: 2.742

2021-07-11T16:15:06.786246313Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Device ST-00019259 has reported a sensor fault. Reason: ['lightning disturber', 'precip failed']

2021-07-11T16:15:06.810480042Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type device_status has been processed, with payload: {}

2021-07-11T16:15:06.886902188Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 106921 WHERE sensorid = 'illuminance'

2021-07-11T16:15:06.901375241Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 0 WHERE sensorid = 'rain_duration_today'

2021-07-11T16:15:06.901468351Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 0 WHERE sensorid = 'rain_rate'

2021-07-11T16:15:06.901519054Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 891 WHERE sensorid = 'solar_radiation'

2021-07-11T16:15:06.912569050Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 3.72 WHERE sensorid = 'uv'

2021-07-11T16:15:06.925894522Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 3.33 WHERE sensorid = 'wind_gust'

2021-07-11T16:15:06.945878498Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 0.11 WHERE sensorid = 'wind_lull'

2021-07-11T16:15:06.960818842Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 1.41 WHERE sensorid = 'wind_speed_avg'

2021-07-11T16:15:07.003335843Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 73.4 WHERE sensorid = 'dewpoint'

2021-07-11T16:15:07.019292250Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 65.0 WHERE sensorid = 'relative_humidity'

2021-07-11T16:15:07.030282950Z DEBUG:weatherflow2mqtt.sqlite:Min/Max SQL: UPDATE high_low SET  min_day = 30.09, min_day_time = 1626020107.0296788 , latest = 30.09 WHERE sensorid = 'sealevel_pressure'

2021-07-11T16:15:07.043910530Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 1 WHERE sensorid = 'lightning_strike_count_today'

2021-07-11T16:15:07.044939631Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 16782152 WHERE sensorid = 'lightning_strike_energy'

2021-07-11T16:15:07.045801677Z DEBUG:weatherflow2mqtt.sqlite:Latest SQL: UPDATE high_low SET latest = 86.6 WHERE sensorid = 'air_temperature'

2021-07-11T16:15:07.081103550Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type obs_st has been processed, with payload: {"station_pressure": 30.09, "air_temperature": 86.6, "relative_humidity": 65.0, "lightning_strike_count": 1, "lightning_strike_count_today": 1, "lightning_strike_distance": 16.78, "lightning_strike_energy": 16782152, "lightning_strike_time": "2021-07-11T12:12:00.624725", "sealevel_pressure": 30.09, "pressure_trend": "Steady", "pressure_trend_value": 0, "air_density": 0.073, "dewpoint": 73.4, "feelslike": 95.2, "wetbulb": 77.1, "delta_t": -52.2, "dewpoint_description": "Oppressive", "temperature_description": "Hot"}

2021-07-11T16:15:07.867566783Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 1.54, "wind_bearing": 73, "wind_direction": "ENE"}

2021-07-11T16:15:09.915751050Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:HUB Reset Flags: PIN,SFT

2021-07-11T16:15:09.916230471Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type hub_status has been processed, with payload: {"uptime": "9 days, 8:07:55"}

2021-07-11T16:15:10.875921861Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 1.72, "wind_bearing": 49, "wind_direction": "NE"}

2021-07-11T16:15:13.875763437Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 1.07, "wind_bearing": 83, "wind_direction": "E"}

2021-07-11T16:15:16.881090015Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 0.65, "wind_bearing": 87, "wind_direction": "E"}

2021-07-11T16:15:19.859498156Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 0.34, "wind_bearing": 197, "wind_direction": "SSW"}

2021-07-11T16:15:19.938222316Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:HUB Reset Flags: PIN,SFT

2021-07-11T16:15:19.938592923Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type hub_status has been processed, with payload: {"uptime": "9 days, 8:08:05"}

2021-07-11T16:15:23.627878354Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 1.03, "wind_bearing": 206, "wind_direction": "SSW"}

2021-07-11T16:15:25.858747301Z DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type rapid_wind has been processed, with payload: {"wind_speed": 1.36, "wind_bearing": 206, "wind_direction": "SSW"}

**Comment by briis** [comment]
I am tight up with work right now, hopefully I can look at this later this week.

**Comment by robertw** [comment]
Well the most recent update so far has not shown this error I don't know whether it was the changes you did and the lightning area but it seems to be running clean at this point I'm going to close this and reopen it only if they are reoccurs thank you
