### ISSUE TITLE
temperature & feels like temperature sensors don't work when exported in homekit

### ISSUE THREAD

**Issue by leonardpitzu** [briis/hass-weatherflow2mqtt#93]
The following error comes up when selecting the title mentioned sensors homekit (HASS bridge).
Also both sensors are added in a HA history in a different section from all other "temperature" sensors (all measured in Celsius)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 269, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 389, in async_update_event_state_callback
    self.async_update_state_callback(event.data.get("new_state"))
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 411, in async_update_state_callback
    self.async_update_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_sensors.py", line 119, in async_update_state
    temperature = temperature_to_homekit(temperature, unit)
  File "/usr/src/homeassistant/homeassistant/components/homekit/util.py", line 367, in temperature_to_homekit
    return round(temp_util.convert(temperature, unit, TEMP_CELSIUS), 1)
  File "/usr/src/homeassistant/homeassistant/util/temperature.py", line 44, in convert
    raise ValueError(UNIT_NOT_RECOGNIZED_TEMPLATE.format(from_unit, TEMPERATURE))
ValueError: ˚C is not a recognized temperature unit.

**Comment by briis** [comment]
Yes, it seems homekit does not like the ˚ in front of the C. I will look at moving this to the official constants for the temperature units.

**Comment by leonardpitzu** [comment]
Had the same trouble when making a custom integration in HA. In the end I just used the constants.

**Comment by briis** [comment]
I just added `sensor.wf_temperature` to Homekit, and I did not get any errors. And that is with the latest released version, which I assume you are running. But I have made edits and implemented the constants from HA, so let us see if that will help you. Will release a new version soon.

**Comment by leonardpitzu** [comment]
Ok, gerat. I will test and report back. Thanks for your support.

**Comment by leonardpitzu** [comment]
checked it in a local build - seems ok, values appear in homekit and temperatures are grouped togehter in HA

**Comment by briis** [comment]
Great thanks. I will look at the other request you send and then release this.

**Comment by briis** [comment]
Closing this, as it has been done.
