### ISSUE TITLE
Changed nothing and now I get error as below any thoughts

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#94]
I changed nothing and will not start ? thank you in advance....

DEBUG:weatherflow2mqtt.weatherflow_mqtt:Skipping Forecast sensor False weather

Traceback (most recent call last):

  File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>

    sys.exit(load_entry_point('weatherflow2mqtt==2.2.1', 'console_scripts', 'weatherflow2mqtt')())

  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-2.2.1-py3.9.egg/weatherflow2mqtt/__main__.py", line 10, in main

  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete

    return future.result()

  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-2.2.1-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 378, in main

TypeError: cannot unpack non-iterable NoneType object

DEBUG:asyncio:Using selector: EpollSelector

**Comment by robertw** [comment]
Sorry guys looks like my unit died not program my bad!

**Comment by briis** [comment]
Hope you get it running again. Else I find WeatherFlow support very responsive.
